Games_Reviews/urls.py
from django.urls import path

from Games_Reviews.views import home, return_data, single_game

app_name = 'Games_Reviews'

urlpatterns = [
    path('api/<str:username>/<str:key>', return_data, name='return_data'),
    path('game/<int:_id>', single_game, name='single_game'),
    path('', home, name='home')
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Games_Reviews.urls'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Games_Reviews/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

from Games_Reviews.utils import generate_api_key


def validate_review_value(value: int):
    if value > 5:
        raise ValidationError('The value cannot be greater than 5.')


class Review(models.Model):
    title = models.CharField(max_length=120)
    reviews = models.PositiveIntegerField(validators=[validate_review_value])
    image = models.ImageField(upload_to='images/%y/%m/')
    developer = models.CharField(max_length=50)
    publisher = models.CharField(max_length=50)
    series = models.CharField(max_length=50)
    platforms = models.CharField(max_length=124)
    release = models.DateField()
    genre = models.CharField(max_length=50)
    mode = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.title


class GenerateKeys(models.Model):
    class Meta:
        verbose_name_plural = 'GenerateKeys'
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    key = models.CharField(default=generate_api_key,
                           editable=False,
                           unique=True,
                           null=False,
                           blank=False,
                           max_length=50)

    def __str__(self) -> str:
        return self.user.username

Games_Reviews/views.py
from django.db.models import Q
from django.http import (Http404, HttpRequest, HttpResponse,
                         HttpResponseNotAllowed, JsonResponse)
from django.shortcuts import render

from Games_Reviews.models import GenerateKeys, Review, User


def return_data(request: HttpRequest, username: str, key: str):
    if request.method == 'POST':
        return HttpResponseNotAllowed(['GET'])
    user = User.objects.filter(username=username)
    _key = GenerateKeys.objects.filter(user_id=user.get().pk)
    if key != _key.get().key:
        return JsonResponse({'error': 'Incorrect key.'}, status=404)
    games = Review.objects.all().values(
        'title',
        'reviews',
        'image',
        'developer',
        'publisher',
        'series',
        'platforms',
        'release',
        'genre',
        'mode'
    )

    games_list = list(games)
    return JsonResponse(games_list, safe=False)


def home(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        search = request.POST.get('query')
        games = Review.objects.filter(
            Q(title__contains=search) |
            Q(platforms__contains=search) |
            Q(publisher__contains=search) |
            Q(reviews__contains=search) |
            Q(release__contains=search)
        )
        context = {
            'games': games
        }
        return render(request, 'index.html', context)

    games = Review.objects.all()
    context = {
        'games': games
    }
    return render(request, 'index.html', context)


def single_game(request: HttpRequest, _id: int) -> HttpResponse:
    game = Review.objects.filter(id=_id)
    context = {
        'game': game
    }
    return render(request, 'single_game.html', context)

Games_Reviews/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/index/style.css" %}">
    <title>Games API</title>
</head>
<body>
    <header>
        <div id="search">
            <form method="POST">
                {% csrf_token %}
                <input type="search" name="query" id="query">
                <input type="submit" value="Search">
            </form>
        </div>
    </header>

    <table border="1">
        <tr>
            <th>Title</th>
            <th>Reviews</th>
            <th>Publisher</th>
            <th>Platforms</th>
            <th>Release</th>
        </tr>
        {% for game in games %}
            <tr>
                <td><a href="{% url "Games_Reviews:single_game" game.id %}">{{ game.title }}</a></td>
                <td><a href="{% url "Games_Reviews:single_game" game.id %}">{{ game.reviews }} of 5⭐.</a></td>
                <td><a href="{% url "Games_Reviews:single_game" game.id %}">{{ game.publisher }}</a></td>
                <td><a href="{% url "Games_Reviews:single_game" game.id %}">{{ game.platforms }}</a></td>
                <td><a href="{% url "Games_Reviews:single_game" game.id %}">{{ game.release }}</a></td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>

Games_Reviews/templates/single_game.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/single_game/style.css" %}">
    <title>Games API</title>
</head>
<body>
    {% for info in game %}
        <img src="{{ info.image.url }}" alt="">
        <h2>{{ info.title }}</h2>
        <h2>{{ info.reviews }} of 5⭐.</h2>
        <h2>Developer: {{ info.developer }}</h2>
        <h2>Publisher: {{ info.publisher }}</h2>
        <h2>Series: {{ info.series }}</h2>
        <h2>Platforms: {{ info.platforms }}</h2>
        <h2>Release: {{ info.release }}</h2>
        <h2>Genre: {{ info.genre }}</h2>
        <h2>Mode: {{ info.mode }}</h2>
    {% endfor %}
    
    <div class="button">
        <a href="{% url "Games_Reviews:home" %}">Return</a>
    </div>
</body>
</html>